<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'BotFramework\\Gateway\\TelegramRequest' => 'get1',
  'BotFramework\\Gateway\\Response' => 'get2',
  'subEntry1' => 'get3',
);

    protected function get1()
    {
        $object = new BotFramework\Gateway\TelegramRequest(786358694);
        return $object;
    }

    protected function get3()
    {
        return $this->delegateContainer->get('BotFramework\\Gateway\\TelegramRequest');
    }

    protected function get2()
    {
        $object = new BotFramework\Gateway\Response($this->get3(), 315);
        return $object;
    }

}
