# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main dev ]
  pull_request:
    branches: [ main dev ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
        # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: Prettier Action
        uses: creyD/prettier_action@v4.0
